"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
type Config = { cloudName: string; apiKey: string; apiSecret: string; uploadFolder: string; isEnabled: boolean };
const empty: Config = { cloudName: "", apiKey: "", apiSecret: "", uploadFolder: "les-epices-de-sulson/products", isEnabled: true };
export default function MediaSettingsPage() {
  const [config, setConfig] = useState(empty); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/settings/media").then((r) => r.json()).then((j) => j.data && setConfig(j.data)).catch(() => toast.error("Configuration média indisponible.")); }, []);
  async function save(action?: "test") { setSaving(true); try { const r = await fetch("/api/settings/media", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...config, action }) }); const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.error); toast.success(action ? "Connexion Cloudinary validée." : "Configuration Cloudinary enregistrée."); } catch (e) { toast.error(e instanceof Error ? e.message : "Échec de la configuration."); } finally { setSaving(false); } }
  return <div className="max-w-3xl mx-auto space-y-6"><div><h1 className="text-xl font-bold text-gray-900">Images produits</h1><p className="text-sm text-gray-500 mt-1">Cloudinary stocke et optimise les images du catalogue. Les clés restent côté serveur.</p></div><div className="bg-white border border-gray-200 rounded-2xl p-6 space-y-5"><label className="block"><span className="text-xs font-bold text-gray-700">Cloud name</span><input value={config.cloudName} onChange={(e) => setConfig({ ...config, cloudName: e.target.value })} className="mt-1 w-full h-11 px-3 rounded-xl border border-gray-300" /></label><div className="grid sm:grid-cols-2 gap-4"><label><span className="text-xs font-bold text-gray-700">API key</span><input value={config.apiKey} onChange={(e) => setConfig({ ...config, apiKey: e.target.value })} className="mt-1 w-full h-11 px-3 rounded-xl border border-gray-300" /></label><label><span className="text-xs font-bold text-gray-700">API secret</span><input type="password" value={config.apiSecret} onChange={(e) => setConfig({ ...config, apiSecret: e.target.value })} className="mt-1 w-full h-11 px-3 rounded-xl border border-gray-300" /></label></div><label className="block"><span className="text-xs font-bold text-gray-700">Dossier d’envoi</span><input value={config.uploadFolder} onChange={(e) => setConfig({ ...config, uploadFolder: e.target.value })} className="mt-1 w-full h-11 px-3 rounded-xl border border-gray-300" /></label><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={config.isEnabled} onChange={(e) => setConfig({ ...config, isEnabled: e.target.checked })} /> Activer les téléversements</label><div className="flex gap-3"><button disabled={saving} onClick={() => save("test")} className="rounded-xl border border-gray-300 px-4 py-2 text-sm font-bold">Tester</button><button disabled={saving} onClick={() => save()} className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Enregistrer</button></div></div></div>;
}
